# Generated by Django 5.2.8 on 2025-11-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(default='published', max_length=20)),
                ('category', models.CharField(default='general', max_length=50)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
