# Generated by Django 5.2.8 on 2025-11-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Squirrel Rusty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.vecteezy.com/photo/39584516-ai-generated-cute-small-rodent-sitting-in-grass-looking-at-camera-generated-by-ai', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='https://www.vecteezy.com/photo/39584516-ai-generated-cute-small-rodent-sitting-in-grass-looking-at-camera-generated-by-ai', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
