# Generated by Django 5.2.8 on 2025-11-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_published_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/024/654/096/small/fluffy-squirrel-munching-on-acorns-in-tree-generated-by-ai-free-photo.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/024/654/096/small/fluffy-squirrel-munching-on-acorns-in-tree-generated-by-ai-free-photo.jpg', null=True),
        ),
    ]
