# Generated by Django 5.2.8 on 2025-12-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image_url_alter_post_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature'), ('adventure', 'Adventure'), ('food', 'Food'), ('friends', 'Friends'), ('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], default='nature', max_length=20),
        ),
    ]
